// packages/vue/src/components/LkpFooter.vue
<template>
    <footer class="lkp-footer" role="contentinfo">
        <div class="lkp-footer-container">
            <div v-if="config.description" class="lkp-footer-description">
                {{ config.description }}
            </div>

            <nav
                v-if="config.columns && config.columns.length"
                class="lkp-footer-nav"
                aria-label="Footer navigation"
            >
                <div
                    v-for="(column, index) in config.columns"
                    :key="index"
                    class="lkp-footer-column"
                >
                    <h3>{{ column.title }}</h3>
                    <ul>
                        <li
                            v-for="(link, linkIndex) in column.links"
                            :key="linkIndex"
                        >
                            <a
                                :href="link.href"
                                class="lkp-link"
                                :target="link.external ? '_blank' : undefined"
                                :rel="
                                    link.external
                                        ? 'noopener noreferrer'
                                        : undefined
                                "
                            >
                                {{ link.label }}
                                <span v-if="link.external" class="lkp-sr-only"
                                    >(opens in new tab)</span
                                >
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div
                v-if="config.institutions && config.institutions.length"
                class="lkp-footer-institutions"
            >
                <div
                    v-for="(institution, index) in config.institutions"
                    :key="index"
                    class="lkp-institution"
                >
                    <a
                        v-if="institution.href"
                        :href="institution.href"
                        :target="institution.external ? '_blank' : undefined"
                        :rel="
                            institution.external
                                ? 'noopener noreferrer'
                                : undefined
                        "
                    >
                        <img
                            v-if="institution.logo"
                            :src="institution.logo"
                            :alt="institution.name"
                        />
                        <span v-else>{{ institution.name }}</span>
                        <span v-if="institution.external" class="lkp-sr-only"
                            >(opens in new tab)</span
                        >
                    </a>
                    <span v-else>
                        <img
                            v-if="institution.logo"
                            :src="institution.logo"
                            :alt="institution.name"
                        />
                        <span v-else>{{ institution.name }}</span>
                    </span>
                </div>
            </div>

            <div v-if="config.copyright" class="lkp-footer-copyright">
                {{ config.copyright }}
            </div>
        </div>
    </footer>
</template>

<script setup lang="ts">
import type { FooterConfig } from "@liverkp/core";

defineProps<{
    config: FooterConfig;
}>();
</script>

// packages/react/src/components/LkpFooter.tsx
import React from "react";
import type { FooterConfig } from "@liverkp/core";

export interface LkpFooterProps {
    config: FooterConfig;
}

export const LkpFooter: React.FC<LkpFooterProps> = ({ config }) => {
    return (
        <footer className="lkp-footer" role="contentinfo">
            <div className="lkp-footer-container">
                {config.description && (
                    <div className="lkp-footer-description">
                        {config.description}
                    </div>
                )}

                {config.columns && config.columns.length > 0 && (
                    <nav
                        className="lkp-footer-nav"
                        aria-label="Footer navigation"
                    >
                        {config.columns.map((column, index) => (
                            <div key={index} className="lkp-footer-column">
                                <h3>{column.title}</h3>
                                <ul>
                                    {column.links.map((link, linkIndex) => (
                                        <li key={linkIndex}>
                                            <a
                                                href={link.href}
                                                className="lkp-link"
                                                target={
                                                    link.external
                                                        ? "_blank"
                                                        : undefined
                                                }
                                                rel={
                                                    link.external
                                                        ? "noopener noreferrer"
                                                        : undefined
                                                }
                                            >
                                                {link.label}
                                                {link.external && (
                                                    <span className="lkp-sr-only">
                                                        (opens in new tab)
                                                    </span>
                                                )}
                                            </a>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </nav>
                )}

                {config.institutions && config.institutions.length > 0 && (
                    <div className="lkp-footer-institutions">
                        {config.institutions.map((institution, index) => (
                            <div key={index} className="lkp-institution">
                                {institution.href ? (
                                    <a
                                        href={institution.href}
                                        target={
                                            institution.external
                                                ? "_blank"
                                                : undefined
                                        }
                                        rel={
                                            institution.external
                                                ? "noopener noreferrer"
                                                : undefined
                                        }
                                    >
                                        {institution.logo ? (
                                            <img
                                                src={institution.logo}
                                                alt={institution.name}
                                            />
                                        ) : (
                                            <span>{institution.name}</span>
                                        )}
                                        {institution.external && (
                                            <span className="lkp-sr-only">
                                                (opens in new tab)
                                            </span>
                                        )}
                                    </a>
                                ) : (
                                    <span>
                                        {institution.logo ? (
                                            <img
                                                src={institution.logo}
                                                alt={institution.name}
                                            />
                                        ) : (
                                            <span>{institution.name}</span>
                                        )}
                                    </span>
                                )}
                            </div>
                        ))}
                    </div>
                )}

                {config.copyright && (
                    <div className="lkp-footer-copyright">
                        {config.copyright}
                    </div>
                )}
            </div>
        </footer>
    );
};
