// packages/vue/src/components/LkpNavMenu.vue
<template>
    <div class="lkp-nav-hamburger">
        <input
            type="checkbox"
            id="lkp-hamburger-toggle"
            class="lkp-hamburger-toggle"
            v-model="menuOpen"
            @keydown.escape="menuOpen = false"
        />
        <label
            for="lkp-hamburger-toggle"
            class="lkp-hamburger"
            :aria-label="menuOpen ? 'Close menu' : 'Open menu'"
            :aria-expanded="menuOpen"
            role="button"
            tabindex="0"
            @keydown.enter.prevent="menuOpen = !menuOpen"
            @keydown.space.prevent="menuOpen = !menuOpen"
        >
            <span class="lkp-slice"></span>
            <span class="lkp-slice"></span>
            <span class="lkp-slice"></span>
        </label>
    </div>

    <div class="lkp-menu-wrapper">
        <nav class="lkp-main-menu" aria-label="Main navigation">
            <div
                v-for="(item, index) in items"
                :key="index"
                class="lkp-menu-item-wrapper"
            >
                <a
                    v-if="item.href"
                    :href="item.href"
                    class="lkp-menu-item"
                    :target="item.external ? '_blank' : undefined"
                    :rel="item.external ? 'noopener noreferrer' : undefined"
                    :aria-haspopup="item.children ? 'true' : undefined"
                    :aria-expanded="item.children ? 'false' : undefined"
                >
                    {{ item.label }}
                    <span v-if="item.external" class="lkp-sr-only"
                        >(opens in new tab)</span
                    >
                </a>
                <div
                    v-else
                    class="lkp-menu-item"
                    :aria-haspopup="item.children ? 'true' : undefined"
                >
                    {{ item.label }}
                </div>

                <div v-if="item.children" class="lkp-submenu" role="menu">
                    <a
                        v-for="(child, childIndex) in item.children"
                        :key="childIndex"
                        :href="child.href || '#'"
                        class="lkp-submenu-item"
                        role="menuitem"
                        :target="child.external ? '_blank' : undefined"
                        :rel="
                            child.external ? 'noopener noreferrer' : undefined
                        "
                    >
                        {{ child.label }}
                        <span v-if="child.external" class="lkp-sr-only"
                            >(opens in new tab)</span
                        >
                    </a>
                </div>
            </div>
        </nav>

        <div v-if="topMenuItems && topMenuItems.length" class="lkp-top-menu">
            <a
                v-for="(item, index) in topMenuItems"
                :key="index"
                :href="item.href || '#'"
                class="lkp-menu-item"
                :target="item.external ? '_blank' : undefined"
                :rel="item.external ? 'noopener noreferrer' : undefined"
            >
                {{ item.label }}
                <span v-if="item.external" class="lkp-sr-only"
                    >(opens in new tab)</span
                >
            </a>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import type { NavMenuItem, TopMenuItem } from "@liverkp/core";

defineProps<{
    items: NavMenuItem[];
    topMenuItems?: TopMenuItem[];
}>();

const menuOpen = ref(false);
</script>

// packages/react/src/components/LkpNavMenu.tsx
import React, { useState } from "react";
import type { NavMenuItem, TopMenuItem } from "@liverkp/core";

export interface LkpNavMenuProps {
    items: NavMenuItem[];
    topMenuItems?: TopMenuItem[];
}

export const LkpNavMenu: React.FC<LkpNavMenuProps> = ({
    items,
    topMenuItems = [],
}) => {
    const [menuOpen, setMenuOpen] = useState(false);

    const toggleMenu = () => setMenuOpen(!menuOpen);

    const handleKeyDown = (event: React.KeyboardEvent) => {
        if (event.key === "Escape") {
            setMenuOpen(false);
        } else if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            toggleMenu();
        }
    };

    return (
        <div>
            <div className="lkp-nav-hamburger">
                <input
                    type="checkbox"
                    id="lkp-hamburger-toggle"
                    className="lkp-hamburger-toggle"
                    checked={menuOpen}
                    onChange={(e) => setMenuOpen(e.target.checked)}
                    onKeyDown={(e) => e.key === "Escape" && setMenuOpen(false)}
                />
                <label
                    htmlFor="lkp-hamburger-toggle"
                    className="lkp-hamburger"
                    aria-label={menuOpen ? "Close menu" : "Open menu"}
                    aria-expanded={menuOpen}
                    role="button"
                    tabIndex={0}
                    onKeyDown={handleKeyDown}
                >
                    <span className="lkp-slice"></span>
                    <span className="lkp-slice"></span>
                    <span className="lkp-slice"></span>
                </label>
            </div>

            <div className="lkp-menu-wrapper">
                <nav className="lkp-main-menu" aria-label="Main navigation">
                    {items.map((item, index) => (
                        <div key={index} className="lkp-menu-item-wrapper">
                            {item.href ? (
                                <a
                                    href={item.href}
                                    className="lkp-menu-item"
                                    target={
                                        item.external ? "_blank" : undefined
                                    }
                                    rel={
                                        item.external
                                            ? "noopener noreferrer"
                                            : undefined
                                    }
                                    aria-haspopup={
                                        item.children ? "true" : undefined
                                    }
                                    aria-expanded={
                                        item.children ? "false" : undefined
                                    }
                                >
                                    {item.label}
                                    {item.external && (
                                        <span className="lkp-sr-only">
                                            (opens in new tab)
                                        </span>
                                    )}
                                </a>
                            ) : (
                                <div
                                    className="lkp-menu-item"
                                    aria-haspopup={
                                        item.children ? "true" : undefined
                                    }
                                >
                                    {item.label}
                                </div>
                            )}

                            {item.children && (
                                <div className="lkp-submenu" role="menu">
                                    {item.children.map((child, childIndex) => (
                                        <a
                                            key={childIndex}
                                            href={child.href || "#"}
                                            className="lkp-submenu-item"
                                            role="menuitem"
                                            target={
                                                child.external
                                                    ? "_blank"
                                                    : undefined
                                            }
                                            rel={
                                                child.external
                                                    ? "noopener noreferrer"
                                                    : undefined
                                            }
                                        >
                                            {child.label}
                                            {child.external && (
                                                <span className="lkp-sr-only">
                                                    (opens in new tab)
                                                </span>
                                            )}
                                        </a>
                                    ))}
                                </div>
                            )}
                        </div>
                    ))}
                </nav>

                {topMenuItems.length > 0 && (
                    <div className="lkp-top-menu">
                        {topMenuItems.map((item, index) => (
                            <a
                                key={index}
                                href={item.href || "#"}
                                className="lkp-menu-item"
                                target={item.external ? "_blank" : undefined}
                                rel={
                                    item.external
                                        ? "noopener noreferrer"
                                        : undefined
                                }
                            >
                                {item.label}
                                {item.external && (
                                    <span className="lkp-sr-only">
                                        (opens in new tab)
                                    </span>
                                )}
                            </a>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};
